-- 1. Разработайте АБ, демонстрирующий работу оператора SELECT с точной выборкой.

-- 2. Разработайте АБ, демонстрирующий работу оператора SELECT с неточной точной выборкой. 
-- Используйте конструкцию WHEN OTHERS секции исключений и встроенную функции 
-- SQLERRM, SQLCODE для диагностирования неточной выборки.

DECLARE
  v_type  AUDITORIUM_TYPE.AUDITORIUM_TYPE%TYPE;
  v_name  AUDITORIUM_TYPE.AUDITORIUM_TYPENAME%TYPE;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Точная выборка');
  BEGIN
    SELECT AUDITORIUM_TYPE, AUDITORIUM_TYPENAME
    INTO v_type, v_name
    FROM AUDITORIUM_TYPE
    WHERE AUDITORIUM_TYPE = 'ЛК';

    DBMS_OUTPUT.PUT_LINE('Результат точной выборки: ' || v_type || ' - ' || v_name);

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Ошибка точной выборки:');
      DBMS_OUTPUT.PUT_LINE('  SQLCODE = ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('  SQLERRM = ' || SQLERRM);
  END;

  DBMS_OUTPUT.PUT_LINE('Неточная выборка');
  BEGIN
    FOR rec IN (
      SELECT AUDITORIUM_TYPE, AUDITORIUM_TYPENAME
      FROM AUDITORIUM_TYPE
      WHERE AUDITORIUM_TYPE LIKE 'Л%'
    )
    LOOP
      DBMS_OUTPUT.PUT_LINE('  ' || rec.AUDITORIUM_TYPE || ' - ' || rec.AUDITORIUM_TYPENAME);
    END LOOP;

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Ошибка при неточной выборке:');
      DBMS_OUTPUT.PUT_LINE('  SQLCODE = ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('  SQLERRM = ' || SQLERRM);
  END;
END;
/

-- 3. Разработайте АБ, демонстрирующий работу конструкции WHEN TO_MANY_ROWS 
-- секции исключений для диагностирования неточной выборки.
SELECT * FROM AUDITORIUM;

DECLARE
  v_AUDITORIUM          AUDITORIUM.AUDITORIUM%TYPE;
  v_AUDITORIUM_NAME     AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_AUDITORIUM_CAPACITY AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
  SELECT AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY
  INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY
  FROM AUDITORIUM
  WHERE AUDITORIUM_TYPE = 'ЛК';
  DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                       ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибочка: ' || SQLCODE || ' ' || SQLERRM);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка');
    DBMS_OUTPUT.PUT_LINE(' SQLCODE = ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE(' SQLERRM = ' || SQLERRM);
end;

-- 4. Разработайте АБ, демонстрирующий возникновение и обработку исключения NO_DATA_FOUND.

DECLARE
  v_AUDITORIUM          AUDITORIUM.AUDITORIUM%TYPE;
  v_AUDITORIUM_NAME     AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_AUDITORIUM_CAPACITY AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
  SELECT AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY
  INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY
  FROM AUDITORIUM
  WHERE AUDITORIUM_TYPE = 'ЛКQWERTY';
  DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                       ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLCODE || ' ' || SQLERRM);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка');
    DBMS_OUTPUT.PUT_LINE(' SQLCODE = ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE(' SQLERRM = ' || SQLERRM);
end;

-- Разработайте АБ, демонстрирующий применение атрибутов неявного курсора.
SELECT * FROM AUDITORIUM;

DECLARE
  v_AUDITORIUM          AUDITORIUM.AUDITORIUM%TYPE;
  v_AUDITORIUM_NAME     AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_AUDITORIUM_CAPACITY AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
  SELECT AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY
  INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY
  FROM AUDITORIUM
  WHERE AUDITORIUM_TYPE = 'ЛК-К';

  IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Запрос нашёл данные.');
  END IF;

  IF SQL%NOTFOUND THEN
    DBMS_OUTPUT.PUT_LINE('Запрос не нашёл данные.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('Количество извлечённых строк: ' || SQL%ROWCOUNT);

  DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                       ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Другая ошибка:');
    DBMS_OUTPUT.PUT_LINE(' SQLCODE = ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE(' SQLERRM = ' || SQLERRM);
END;


-- 5. Разработайте АБ, демонстрирующий применение оператора UPDATE 
-- совместно с операторами COMMIT/ROLLBACK.
SELECT * FROM AUDITORIUM;
UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 15 WHERE AUDITORIUM = '236-1';

DECLARE
  v_old_capacity AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
  v_new_capacity AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
  SELECT AUDITORIUM_CAPACITY 
  INTO v_old_capacity
  FROM AUDITORIUM
  WHERE AUDITORIUM = '236-1';

  DBMS_OUTPUT.PUT_LINE('Текущая вместимость аудитории 206-1: ' || v_old_capacity);

  UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 16 WHERE AUDITORIUM = '236-1';

  SELECT AUDITORIUM_CAPACITY 
  INTO v_new_capacity
  FROM AUDITORIUM
  WHERE AUDITORIUM = '236-1';

  DBMS_OUTPUT.PUT_LINE('Текущая вместимость аудитории 206-1: ' || v_new_capacity);
  COMMIT;

  SELECT AUDITORIUM_CAPACITY 
  INTO v_new_capacity
  FROM AUDITORIUM
  WHERE AUDITORIUM = '236-1';

  DBMS_OUTPUT.PUT_LINE('Обновленная вместимость аудитории 206-1 после коммита: ' || v_new_capacity);

  UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 17 WHERE AUDITORIUM = '236-1';

  SELECT AUDITORIUM_CAPACITY 
  INTO v_new_capacity
  FROM AUDITORIUM
  WHERE AUDITORIUM = '236-1';

  DBMS_OUTPUT.PUT_LINE('Текущая вместимость аудитории 206-1: ' || v_new_capacity);
  ROLLBACK;

  SELECT AUDITORIUM_CAPACITY 
  INTO v_new_capacity
  FROM AUDITORIUM
  WHERE AUDITORIUM = '236-1';

  DBMS_OUTPUT.PUT_LINE('Вместимость аудитории 206-1 после отката: ' || v_new_capacity);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Произошла ошибка: ' || SQLERRM);
    ROLLBACK;
END;

-- 6. Продемонстрируйте оператор UPDATE, вызывающий нарушение целостности в базе данных. Обработайте возникшее исключение.
SELECT * FROM AUDITORIUM;

DECLARE
BEGIN
  UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 'QWERTY' WHERE AUDITORIUM_CAPACITY = 90;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLCODE || ' ' || SQLERRM);
    ROLLBACK;
end;

-- 7. Разработайте АБ, демонстрирующий применение оператора INSERT совместно с операторами COMMIT/ROLLBACK.
SELECT * FROM AUDITORIUM;
DELETE FROM AUDITORIUM WHERE AUDITORIUM = '222-1';
SELECT * FROM AUDITORIUM WHERE AUDITORIUM = '222-1';
SELECT * FROM AUDITORIUM WHERE AUDITORIUM = '333-1';



DECLARE
  v_AUDITORIUM          AUDITORIUM.AUDITORIUM%TYPE;
  v_AUDITORIUM_NAME     AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_AUDITORIUM_CAPACITY AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
  INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE)
  VALUES ('222-1', '222-1', 16, 'ЛК')
  RETURNING AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY 
  INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY;

  DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                       ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);
  COMMIT;

  INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE)
  VALUES ('333-1', '333-2', 16, 'ЛК')
  RETURNING AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY 
  INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY;

  DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                       ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);
  ROLLBACK;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLCODE || ' ' || SQLERRM);
    ROLLBACK;
end;


-- 8. Продемонстрируйте оператор INSERT, вызывающий нарушение целостности в базе данных. Обработайте возникшее исключение.
SELECT * FROM AUDITORIUM;

DECLARE
BEGIN
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY)
values ('429-4', '429-4', 90, 90);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLCODE || ' ' || SQLERRM);
    ROLLBACK;
end;

-- 9. Разработайте АБ, демонстрирующий применение оператора DELETE совместно с операторами COMMIT/ROLLBACK.

SELECT * FROM AUDITORIUM;

DECLARE
  v_count_before NUMBER;
  v_count_after NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count_before FROM AUDITORIUM;
  DBMS_OUTPUT.PUT_LINE('Количество записей до удаления: ' || v_count_before);
  DELETE FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'ЛБ-К';
  SELECT COUNT(*) INTO v_count_after FROM AUDITORIUM;
  DBMS_OUTPUT.PUT_LINE('Количество записей после удаления: ' || v_count_after);
  
  --COMMIT;
  
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Изменения были откачены.');
  
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Произошла ошибка. Изменения были отменены.');
END;

-- 10. Продемонстрируйте оператор DELETE, вызывающий нарушение целостности в базе данных. Обработайте возникшее исключение.
SELECT * FROM AUDITORIUM_TYPE;

BEGIN
DELETE FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = 'ЛК';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLCODE || ' ' || SQLERRM);
    ROLLBACK;
end;

-- 11. Создайте анонимный блок, распечатывающий таблицу TEACHER с применением 
-- явного курсора LOOP-цикла. Считанные данные должны быть записаны в переменные, 
-- объявленные с применением опции %TYPE.
SELECT * FROM TEACHER;

DECLARE
  v_TEACHER      TEACHER.TEACHER%TYPE;
  v_TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
  v_PULPIT       TEACHER.PULPIT%TYPE;
  CURSOR c_TEACHER IS
    SELECT TEACHER, TEACHER_NAME, PULPIT FROM TEACHER;
BEGIN
  FOR i IN c_TEACHER
    LOOP
      v_TEACHER := i.TEACHER;
      v_TEACHER_NAME := i.TEACHER_NAME;
      v_PULPIT := i.PULPIT;
      DBMS_OUTPUT.PUT_LINE('TEACHER: ' || v_TEACHER || ', TEACHER_NAME: ' || v_TEACHER_NAME || ', PULPIT: ' ||
                           v_PULPIT);
    END LOOP;
END;

-- 12. Создайте АБ, распечатывающий таблицу SUBJECT с применением явного курсора и WHILE-цикла. 

DECLARE
  v_SUBJECT SUBJECT%ROWTYPE;
  CURSOR c_SUBJECT IS
    SELECT * FROM SUBJECT;
BEGIN
  OPEN c_SUBJECT;
  WHILE TRUE
    LOOP
      FETCH c_SUBJECT 
      INTO v_SUBJECT;
      EXIT WHEN c_SUBJECT%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('SUBJECT: ' || v_SUBJECT.SUBJECT || ', SUBJECT_NAME: ' || v_SUBJECT.SUBJECT_NAME ||
                           ', PULPIT: ' || v_SUBJECT.PULPIT);
    END LOOP;
END;

-- 13. Создайте АБ, распечатывающий все кафедры (таблица PULPIT) и фамилии всех преподавателей (TEACHER) использовав
-- соединение (JOIN) PULPIT и TEACHER и с применением явного курсора и FOR-цикла.
DECLARE
  v_PULPIT         PULPIT.PULPIT%TYPE;
  v_PULPIT_NAME    PULPIT.PULPIT_NAME%TYPE;
  v_FACULTY        PULPIT.FACULTY%TYPE;
  v_TEACHER        TEACHER.TEACHER%TYPE;
  v_TEACHER_NAME   TEACHER.TEACHER_NAME%TYPE;
  v_PULPIT_TEACHER PULPIT.PULPIT%TYPE;
  CURSOR c_PULPIT_TEACHER IS
    SELECT PULPIT.PULPIT, PULPIT.PULPIT_NAME, PULPIT.FACULTY,
           TEACHER.TEACHER, TEACHER.TEACHER_NAME
    FROM PULPIT JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT;
BEGIN
  FOR i IN c_PULPIT_TEACHER
    LOOP
      v_PULPIT := i.PULPIT;
      v_PULPIT_NAME := i.PULPIT_NAME;
      v_FACULTY := i.FACULTY;
      v_TEACHER := i.TEACHER;
      v_TEACHER_NAME := i.TEACHER_NAME;
      DBMS_OUTPUT.PUT_LINE('PULPIT: ' || v_PULPIT || ', PULPIT_NAME: ' || v_PULPIT_NAME || ', FACULTY: ' || v_FACULTY ||
                           ', TEACHER: ' || v_TEACHER || ', TEACHER_NAME: ' || v_TEACHER_NAME);
    END LOOP;
END;

-- 14. Создайте АБ, распечатывающий следующие списки аудиторий: 
-- все аудитории (таблица AUDITORIUM) с вместимостью меньше 20, от 21-30, от 31-60, от 61 до 80, от 81 и выше. 

DECLARE
  CURSOR c_aud (p_min NUMBER, p_max NUMBER) IS
    SELECT AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY
    FROM AUDITORIUM
    WHERE AUDITORIUM_CAPACITY BETWEEN p_min AND p_max
    ORDER BY AUDITORIUM_CAPACITY;

  v_aud   AUDITORIUM.AUDITORIUM%TYPE;
  v_name  AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_cap   AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;

BEGIN
  DBMS_OUTPUT.PUT_LINE('===== 0–20 =====');

  OPEN c_aud(0, 20);
  LOOP
    FETCH c_aud INTO v_aud, v_name, v_cap;
    EXIT WHEN c_aud%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(v_aud || ' | ' || v_name || ' | ' || v_cap);
  END LOOP;
  CLOSE c_aud;

  DBMS_OUTPUT.PUT_LINE('===== 21–30 =====');

  OPEN c_aud(21, 30);
  FETCH c_aud INTO v_aud, v_name, v_cap;

  WHILE c_aud%FOUND LOOP
    DBMS_OUTPUT.PUT_LINE(v_aud || ' | ' || v_name || ' | ' || v_cap);
    FETCH c_aud INTO v_aud, v_name, v_cap;
  END LOOP;

  CLOSE c_aud;

  DBMS_OUTPUT.PUT_LINE('===== 31–60 =====');

  FOR rec IN c_aud(31, 60) LOOP
    DBMS_OUTPUT.PUT_LINE(rec.AUDITORIUM || ' | ' ||
                         rec.AUDITORIUM_NAME || ' | ' ||
                         rec.AUDITORIUM_CAPACITY);
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('===== 61–80 =====');

  FOR rec IN c_aud(61, 80) LOOP
    DBMS_OUTPUT.PUT_LINE(rec.AUDITORIUM || ' | ' ||
                         rec.AUDITORIUM_NAME || ' | ' ||
                         rec.AUDITORIUM_CAPACITY);
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('===== 81+ =====');

  FOR rec IN c_aud(81, 9999) LOOP
    DBMS_OUTPUT.PUT_LINE(rec.AUDITORIUM || ' | ' ||
                         rec.AUDITORIUM_NAME || ' | ' ||
                         rec.AUDITORIUM_CAPACITY);
  END LOOP;
END;
/

-- 15. Создайте AБ. Объявите курсорную переменную с помощью системного типа refcursor. 

DECLARE
  v_AUDITORIUM          AUDITORIUM.AUDITORIUM%TYPE;
  v_AUDITORIUM_NAME     AUDITORIUM.AUDITORIUM_NAME%TYPE;
  v_AUDITORIUM_CAPACITY AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
  c_AUDITORIUM          SYS_REFCURSOR;
BEGIN
  OPEN c_AUDITORIUM FOR
    SELECT AUDITORIUM,
           AUDITORIUM_NAME,
           AUDITORIUM_CAPACITY
    FROM AUDITORIUM
    WHERE AUDITORIUM_TYPE = 'ЛК';

  LOOP
    FETCH c_AUDITORIUM INTO v_AUDITORIUM, v_AUDITORIUM_NAME, v_AUDITORIUM_CAPACITY;
    EXIT WHEN c_AUDITORIUM%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('AUDITORIUM: ' || v_AUDITORIUM || ', AUDITORIUM_NAME: ' || v_AUDITORIUM_NAME ||
                         ', AUDITORIUM_CAPACITY: ' || v_AUDITORIUM_CAPACITY);
  END LOOP;
  CLOSE c_AUDITORIUM;
end;

-- 16. Создайте AБ. Продемонстрируйте понятие курсорный подзапрос

DECLARE
   CURSOR task16 IS
      SELECT AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
      FROM AUDITORIUM
      WHERE AUDITORIUM_TYPE = (
         SELECT AUDITORIUM_TYPE FROM AUDITORIUM WHERE AUDITORIUM_NAME = '429-4'
      );
   auditorium_id AUDITORIUM.AUDITORIUM%TYPE;
   auditorium_name AUDITORIUM.AUDITORIUM_NAME%TYPE;
   auditorium_type AUDITORIUM.AUDITORIUM_TYPE%TYPE;
   auditorium_capacity AUDITORIUM.AUDITORIUM_CAPACITY%TYPE;
BEGIN
   OPEN task16;
   LOOP
      FETCH task16 
      INTO auditorium_id, auditorium_name, auditorium_type, auditorium_capacity;
      EXIT WHEN task16%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(
         'Аудитория: ' || auditorium_id ||
         ', Название: ' || auditorium_name ||
         ', Тип: ' || auditorium_type ||
         ', Вместимость: ' || auditorium_capacity
      );
   END LOOP;
   CLOSE task16;
END;

-- 17. Создайте AБ. Уменьшите вместимость всех аудиторий (таблица AUDITORIUM)вместимостью от 40 до 80 на 10%. 
-- Используйте явный курсор с параметрами, цикл FOR, конструкцию UPDATE CURRENT OF.
SELECT * FROM AUDITORIUM;
ROLLBACK;

DECLARE
  CURSOR c_AUDITORIUM IS
    SELECT * FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY >= 40 and AUDITORIUM_CAPACITY <= 80 FOR UPDATE;
BEGIN
  FOR i IN c_AUDITORIUM
    LOOP
      UPDATE AUDITORIUM
      SET AUDITORIUM_CAPACITY = AUDITORIUM_CAPACITY * 0.9
      WHERE CURRENT OF c_AUDITORIUM;
    END LOOP;
end;

-- 18. Создайте AБ. Удалите все аудитории (таблица AUDITORIUM) вместимостью от 0 до 20. 
-- Используйте явный курсор с параметрами, цикл WHILE, конструкцию UPDATE CURRENT OF.
SELECT * FROM AUDITORIUM;
ROLLBACK;

DECLARE
  v_AUDITORIUM AUDITORIUM.AUDITORIUM%TYPE;
  CURSOR c_AUDITORIUM IS
    SELECT AUDITORIUM FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY >= 0 and AUDITORIUM_CAPACITY <= 20 FOR UPDATE;
BEGIN
  OPEN c_AUDITORIUM;
  LOOP
    FETCH c_AUDITORIUM INTO v_AUDITORIUM;
    EXIT WHEN c_AUDITORIUM%NOTFOUND;
    DELETE FROM AUDITORIUM WHERE CURRENT OF c_AUDITORIUM;
  END LOOP;

  CLOSE c_AUDITORIUM;
end;

-- 19. Создайте AБ. Продемонстрируйте применение псевдостолбца ROWID в операторах UPDATE и DELETE.
DECLARE
  CURSOR c_AUDITORIUM IS
    SELECT ROWID FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY >= 0 and AUDITORIUM_CAPACITY <= 20 FOR UPDATE;
BEGIN
  FOR i IN c_AUDITORIUM
    LOOP
      UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = AUDITORIUM_CAPACITY * 0.9 WHERE ROWID = i.ROWID;
      DELETE FROM AUDITORIUM WHERE ROWID = i.ROWID;
    END LOOP;
end;

-- 20. Распечатайте в одном цикле всех преподавателей (TEACHER), разделив группами по три (отделите группы линией -------------).

DECLARE
  v_TEACHER      TEACHER.TEACHER%TYPE;
  v_TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
  v_PULPIT       TEACHER.PULPIT%TYPE;
  CURSOR c_TEACHER IS
    SELECT TEACHER, TEACHER_NAME,PULPIT FROM TEACHER;
BEGIN
  OPEN c_TEACHER;
  LOOP
    FETCH c_TEACHER INTO v_TEACHER, v_TEACHER_NAME, v_PULPIT;
    EXIT WHEN c_TEACHER%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('TEACHER: ' || v_TEACHER || ', TEACHER_NAME: ' || v_TEACHER_NAME || ', PULPIT: ' ||
                         v_PULPIT);
    IF MOD(c_TEACHER%ROWCOUNT, 3) = 0 THEN
      DBMS_OUTPUT.PUT_LINE('-----------------');
    END IF;
  END LOOP;

  CLOSE c_TEACHER;
end;