ALTER SESSION SET CONTAINER = ORCLPDB1;
SHOW CON_NAME;

DROP TABLE STUDENT;

--1
CREATE TABLE STUDENT
(
  STUDENT       VARCHAR2(20) PRIMARY KEY,
  STUDENT_NAME  VARCHAR2(100) UNIQUE,
  PULPIT        CHAR(20),
  CONSTRAINT FK_STUDENT_PULPIT
    FOREIGN KEY (PULPIT)
    REFERENCES PULPIT (PULPIT)
);

-- 2
INSERT INTO STUDENT VALUES ('S001', 'ИВАНОВ ИВАН', 'ИСиТ');
INSERT INTO STUDENT VALUES ('S002', 'ПЕТРОВ ПЕТР', 'ИСиТ');
INSERT INTO STUDENT VALUES ('S003', 'СИДОРОВ АЛЕКСЕЙ', 'ПОиСОИ');
INSERT INTO STUDENT VALUES ('S004', 'СМИРНОВ НИКОЛАЙ', 'ЛВ');
INSERT INTO STUDENT VALUES ('S005', 'ИЛЬИН ДМИТРИЙ', 'ОВ');
INSERT INTO STUDENT VALUES ('S006', 'МОРОЗОВА ОЛЬГА', 'ОВ');
INSERT INTO STUDENT VALUES ('S007', 'КУЗНЕЦОВ СЕРГЕЙ', 'ЛУ');
INSERT INTO STUDENT VALUES ('S008', 'СОЛОВЬЕВ ДЕНИС', 'ЛПиСПС');
INSERT INTO STUDENT VALUES ('S009', 'ПАВЛОВ АЛЕКСАНДР', 'ТЛ');
INSERT INTO STUDENT VALUES ('S010', 'ИГНАТОВ ИГОРЬ', 'ЛМиЛЗ');

SELECT * FROM STUDENT;
SELECT * FROM PULPIT;

--3
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_OPERATORS_BEFORE
BEFORE INSERT OR DELETE OR UPDATE ON STUDENT
BEGIN
  DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_OPERATORS_BEFORE');
END;
/

INSERT INTO STUDENT (STUDENT, STUDENT_NAME, PULPIT) VALUES ('S011', 'NewStudent', 'ИСиТ');
UPDATE STUDENT SET STUDENT_NAME = 'Update Student' WHERE STUDENT = 'S011';
DELETE FROM STUDENT WHERE STUDENT = 'S011';

--5
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_ROW_BEFORE
BEFORE INSERT OR DELETE OR UPDATE ON STUDENT FOR EACH ROW
BEGIN
  IF INSERTING THEN
    DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_ROW_INSERTING_BEFORE');
  ELSIF UPDATING THEN
    DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_ROW_UPDATING_BEFORE');
  ELSIF DELETING THEN
    DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_ROW_DELETING_BEFORE');
  END IF;
END;
/

INSERT INTO STUDENT (STUDENT, STUDENT_NAME, PULPIT) VALUES ('S011', 'NewStudent', 'ИСиТ');
UPDATE STUDENT SET STUDENT_NAME = STUDENT_NAME WHERE 0 = 0;
DELETE FROM STUDENT WHERE STUDENT = 'S011';

--7
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_OPERATORS_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
BEGIN
  DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_OPERATORS_AFTER');
END;
/

--8
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_ROW_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
BEGIN
  DBMS_OUTPUT.PUT_LINE('STUDENT_TRIGGER_ROW_AFTER');
END;
/

INSERT INTO STUDENT (STUDENT, STUDENT_NAME, PULPIT) VALUES ('S011', 'NewStudent', 'ИСиТ');
UPDATE STUDENT SET STUDENT_NAME = STUDENT_NAME WHERE 0 = 0;
DELETE FROM STUDENT WHERE STUDENT = 'S011';

--9
CREATE TABLE AUDIT_LOG
(
  OPERATION_DATE DATE,
  OPERATION_TYPE VARCHAR2(100),
  TRIGGER_NAME   VARCHAR2(100)
);

DROP TABLE AUDIT_LOG

--10
CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_OPERATORS_BEFORE
BEFORE INSERT OR DELETE OR UPDATE ON STUDENT
BEGIN
  INSERT INTO AUDIT_LOG
  VALUES (SYSDATE, 'OPERATORS BEFORE', 'STUDENT_TRIGGER_OPERATORS_BEFORE');
END;
/

CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_ROW_BEFORE
BEFORE INSERT OR DELETE OR UPDATE ON STUDENT FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_LOG
  VALUES (SYSDATE, 'ROW BEFORE', 'STUDENT_TRIGGER_ROW_BEFORE');
END;
/

CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_OPERATORS_AFTER
AFTER INSERT OR DELETE OR UPDATE ON STUDENT
BEGIN
  INSERT INTO AUDIT_LOG
  VALUES (SYSDATE, 'OPERATORS AFTER', 'STUDENT_TRIGGER_OPERATORS_AFTER');
END;
/

CREATE OR REPLACE TRIGGER STUDENT_TRIGGER_ROW_AFTER
AFTER INSERT OR DELETE OR UPDATE ON STUDENT FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_LOG
  VALUES (SYSDATE, 'ROW AFTER', 'STUDENT_TRIGGER_ROW_AFTER');
END;
/

UPDATE STUDENT SET STUDENT_NAME = STUDENT_NAME WHERE 0 = 0;
SELECT * FROM AUDIT_LOG;
DELETE FROM AUDIT_LOG;

--11
INSERT INTO STUDENT (STUDENT, STUDENT_NAME, PULPIT) VALUES ('S001', 'Иванов Иван', 'ИСиТ');

--12
DROP TABLE STUDENT;
FLASHBACK TABLE STUDENT TO BEFORE DROP;

SELECT * FROM STUDENT;

CREATE OR REPLACE TRIGGER BEFORE_DROP
BEFORE DROP ON ADMINCP.SCHEMA
BEGIN
  IF ORA_DICT_OBJ_NAME = 'STUDENT' THEN
    RAISE_APPLICATION_ERROR(-20001, 'НЕЛЬЗЯ УДАЛЯТЬ ТАБЛИЦУ STUDENT');
  END IF;
END;
/

DROP TRIGGER BEFORE_DROP;

--13
DROP TABLE AUDIT_LOG;
FLASHBACK TABLE AUDIT_LOG TO BEFORE DROP;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS;

--14
CREATE OR REPLACE VIEW STUDENT_VIEW AS SELECT * FROM STUDENT;

CREATE OR REPLACE TRIGGER STUDENT_VIEW_TRIGGER
INSTEAD OF INSERT ON STUDENT_VIEW FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_LOG
  VALUES (SYSDATE, 'INSTEAD OF INSERT', 'STUDENT_VIEW_TRIGGER');

  INSERT INTO STUDENT
  VALUES (:NEW.STUDENT, 'actual', :NEW.PULPIT);
END;
/

INSERT INTO STUDENT_VIEW VALUES ('S018', 'Old', 'ИСиТ');

DELETE FROM STUDENT WHERE STUDENT = 'S018';

SELECT * FROM STUDENT;
SELECT * FROM AUDIT_LOG;
DELETE FROM AUDIT_LOG