ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS';

SHOW CON_NAME
--create
CREATE TABLESPACE T1
DATAFILE 'T1_HPO.DBF'
SIZE 7M
AUTOEXTEND ON
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE T2
DATAFILE 'T2_HPO.DBF'
SIZE 7M
AUTOEXTEND ON
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE T3
DATAFILE 'T3_HPO.DBF'
SIZE 7M
AUTOEXTEND ON
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE T4
DATAFILE 'T4_HPO.DBF'
SIZE 7M
AUTOEXTEND ON
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

--set
ALTER USER ADMINCP QUOTA UNLIMITED ON T1;
ALTER USER ADMINCP QUOTA UNLIMITED ON T2;
ALTER USER ADMINCP QUOTA UNLIMITED ON T3;
ALTER USER ADMINCP QUOTA UNLIMITED ON T4;


--drop
DROP TABLESPACE T1 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE T2 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE T3 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE T4 INCLUDING CONTENTS AND DATAFILES;

--1
DROP TABLE T_RANGE;

CREATE TABLE T_RANGE
(
    ID      NUMBER,
    TIME_ID DATE
)
PARTITION BY RANGE (ID)
(
    PARTITION P0   VALUES LESS THAN (100)      TABLESPACE T1,
    PARTITION P1   VALUES LESS THAN (200)      TABLESPACE T2,
    PARTITION P2   VALUES LESS THAN (300)      TABLESPACE T3,
    PARTITION PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE T4
);

BEGIN
    FOR I IN 1 .. 400 LOOP
        INSERT INTO T_RANGE (ID, TIME_ID)
        VALUES (I, SYSDATE);
    END LOOP;
END;
/

SELECT * FROM T_RANGE PARTITION (P0);
SELECT * FROM T_RANGE PARTITION (P1);
SELECT * FROM T_RANGE PARTITION (P2);
SELECT * FROM T_RANGE PARTITION (PMAX);

SELECT TABLE_NAME,
       PARTITION_NAME,
       HIGH_VALUE,
       TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

--2
DROP TABLE T_INTERVAL;

CREATE TABLE T_INTERVAL
(
    ID      NUMBER,
    TIME_ID DATE
)
PARTITION BY RANGE (TIME_ID)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P0 VALUES LESS THAN (TO_DATE('01-12-2010', 'DD-MM-YYYY')) TABLESPACE T1,
    PARTITION P1 VALUES LESS THAN (TO_DATE('01-12-2015', 'DD-MM-YYYY')) TABLESPACE T2,
    PARTITION P2 VALUES LESS THAN (TO_DATE('01-12-2020', 'DD-MM-YYYY')) TABLESPACE T3
);

INSERT INTO T_INTERVAL VALUES (50,  DATE '2008-02-01');
INSERT INTO T_INTERVAL VALUES (105, DATE '2009-01-01');
INSERT INTO T_INTERVAL VALUES (105, DATE '2007-01-01');
INSERT INTO T_INTERVAL VALUES (205, DATE '2019-01-01');
INSERT INTO T_INTERVAL VALUES (305, DATE '2013-01-01');
INSERT INTO T_INTERVAL VALUES (405, DATE '2017-01-01');
INSERT INTO T_INTERVAL VALUES (505, DATE '2022-01-01');

COMMIT;

SELECT * FROM T_INTERVAL PARTITION (P0);


SELECT TABLE_NAME,
       PARTITION_NAME,
       HIGH_VALUE,
       TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_INTERVAL';

--3
DROP TABLE T_HASH;

CREATE TABLE T_HASH
(
    STR VARCHAR2(50),
    ID  NUMBER
)
PARTITION BY HASH (STR)
(
    PARTITION K0 TABLESPACE T1,
    PARTITION K1 TABLESPACE T2,
    PARTITION K2 TABLESPACE T3,
    PARTITION K3 TABLESPACE T4
);

INSERT INTO T_HASH VALUES ('QWERTY',      1);
INSERT INTO T_HASH VALUES ('SOME STRING', 2);
INSERT INTO T_HASH VALUES ('DB LOVER',    3);
INSERT INTO T_HASH VALUES ('BBBBBBBB',    4);
INSERT INTO T_HASH VALUES ('XX',           7);
INSERT INTO T_HASH VALUES ('UUUU',        14);
INSERT INTO T_HASH VALUES ('FUTURE',      32);
INSERT INTO T_HASH VALUES ('FUTURE',      33);

COMMIT;

SELECT * FROM T_HASH PARTITION (K0);
SELECT * FROM T_HASH PARTITION (K1);
SELECT * FROM T_HASH PARTITION (K2);
SELECT * FROM T_HASH PARTITION (K3);

SELECT TABLE_NAME,
       PARTITION_NAME,
       HIGH_VALUE,
       TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_HASH';


--4
DROP TABLE T_LIST;

CREATE TABLE T_LIST
(
    OBJ CHAR(3)
)
PARTITION BY LIST (OBJ)
(
    PARTITION L0 VALUES ('A')        TABLESPACE T1,
    PARTITION L1 VALUES ('B')        TABLESPACE T2,
    PARTITION L2 VALUES ('C')        TABLESPACE T3,
    PARTITION L3 VALUES (DEFAULT)    TABLESPACE T4
);

INSERT INTO T_LIST VALUES ('A');
INSERT INTO T_LIST VALUES ('B');
INSERT INTO T_LIST VALUES ('C');
INSERT INTO T_LIST VALUES ('D');
INSERT INTO T_LIST VALUES ('E');

COMMIT;

SELECT * FROM T_LIST PARTITION (L0);
SELECT * FROM T_LIST PARTITION (L1);
SELECT * FROM T_LIST PARTITION (L2);
SELECT * FROM T_LIST PARTITION (L3);

--6
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;

UPDATE T_RANGE
SET ID = 2
WHERE ID = 300;

ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;

UPDATE T_INTERVAL
SET TIME_ID = DATE '2017-02-01'
WHERE ID = 50;

ALTER TABLE T_HASH ENABLE ROW MOVEMENT;

UPDATE T_HASH
SET STR = 'ZXCVBNM'
WHERE ID = 3;

ALTER TABLE T_LIST ENABLE ROW MOVEMENT;

UPDATE T_LIST
SET OBJ = 'B'
WHERE OBJ = 'A';

--7
ALTER TABLE T_RANGE
MERGE PARTITIONS P1, P2
INTO PARTITION P5
TABLESPACE T4;

SELECT * FROM T_RANGE PARTITION (P1);
SELECT * FROM T_RANGE PARTITION (P5);
--8
ALTER TABLE T_RANGE
SPLIT PARTITION P5 AT (200)
INTO
(
    PARTITION P1 TABLESPACE T1,
    PARTITION P2 TABLESPACE T2
);

--9
DROP TABLE T_RANGE1;

CREATE TABLE T_RANGE1
(
    ID      NUMBER,
    TIME_ID DATE
);

ALTER TABLE T_RANGE
EXCHANGE PARTITION P0
WITH TABLE T_RANGE1
WITHOUT VALIDATION;

SELECT * FROM T_RANGE PARTITION (P1);
SELECT * FROM T_RANGE1;
